title = "Nicolás Camañes"
baseURL = "https://nicolascamanesantolin.github.io/"
languageCode = "en-us"
theme = ["ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
paginate = 12
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 12

[languages]
  [languages.en]
    title = "Nicolás Camañes"
    weight = 1
    contentDir = "content/en"
  [languages.es]
    title = "Nicolás Camañes"
    weight = 2
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Nicolás Camañes"
  favicon = "/favicon.svg"
  description = "Data Scientist Portfolio"
  body_classes = "portfolio"
  background_color_class = ""
  recent_posts_number = 6
  custom_css = ["custom.css"]
  github = "https://github.com/nicolascamanesantolin"
  linkedin = "https://www.linkedin.com/in/nicol%C3%A1s-cama%C3%B1es-antol%C3%ADn-01278024a"

[markup.goldmark.renderer]
  unsafe = true